name: Meta File Check (github-hosted ubuntu-latest)
on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - main
    paths:
      - Assets/**
      - Packages/**
  workflow_dispatch: {}

jobs:
  meta-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout This Repository
        uses: actions/checkout@v4.1.5
        with:
          submodules: false
          lfs: true
      - name: Unity meta files check (github-hosted ubuntu-latest)
        uses: DeNA/unity-meta-check@v4.0.0
